### ISSUE TITLE
A problem occured when install

### ISSUE THREAD

**Issue by Danilo0120** [EOS-Nation/eos-encrypt#1]
$ npm install --save eos-encrypt
npm WARN saveError ENOENT: no such file or directory, open '/home/huang/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/huang/package.json'
npm WARN huang No description
npm WARN huang No repository field.
npm WARN huang No README data
npm WARN huang No license field.

**Comment by DenisCarriere** [comment]
Fixed, better late than never 😄

**Comment by dominic-healid** [comment]
how to use this via script tag?
